//arrays -> vetores, matrizes
// estrutura e dados para armazenar um conjunto de elemento

let frutas = ["Banana", "maçã", "melancia"]; //array tamanho 3
console.log(frutas);
console.log (frutas [1]);

let numeros = new Array(10,2,6,7)
console.log(numeros);

let arrayVazio = [];
console.log(arrayVazio);
arrayVazio(0) = "Marcos";
console.log(arrayVazio);

//Tamanho de array -> length
let dados = [32,4,20,6]; //tamanho 5 -> length 5
console.log(dados.lenght);